# Generated by Django 3.1.2 on 2020-11-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_stripepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
