# Generated by Django 3.1.2 on 2020-11-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_doorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('Bank', 'Bank'), ('Door', 'Door')], max_length=20),
        ),
    ]
